#!/bin/bash
### BEGIN INIT INFO
# Provides:          monitor_pi_net
# Required-Start:    $all
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: monitor local network and internet access via ping (also provides some basic info about Raspberry Pi itself)
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin

. /lib/init/vars.sh
. /lib/lsb/init-functions


case "$1" in 
start)
   /usr/bin/monitor_pi_net.sh &
   echo $!>/var/run/monitor_pi_net.pid
   ;;
stop)
   kill `cat /var/run/monitor_pi_net.pid`
   rm /var/run/monitor_pi_net.pid
   ;;
restart)
   $0 stop
   $0 start
   ;;
reload)
   cat /var/lib/monitor_pi_net/index.tmpl > /var/log/monitor_pi_net/index.html
   cat /var/lib/monitor_pi_net/styles.css > /var/log/monitor_pi_net/styles.css
   ;;
status)
   if [ -e /var/run/monitor_pi_net.pid ]; then
      echo monitor_pi_net.sh is running, pid=`cat /var/run/monitor_pi_net.pid`
   else
      echo monitor_pi_net.sh is NOT running
      exit 1
   fi
   ;;
*)
   echo "Usage: $0 {start|stop|status|restart|reload}"
esac

exit 0
